version: '3'
services:
  photostad-service:
    container_name: 'photostad-cont'
    image: 'photostad:v1'
    build:
      context: .
    environment:
      - TZ=Asia/Bangkok
    hostname: photostad-service
    ports:
      - '8087:8082'
    volumes:
      - /var/lib/jenkins/workspace/photostad/access-refresh-token-keys/:/workspace/access-refresh-token-keys/
